author = "Simanga Hendry Khoza"
baseurl = "/"
canonifyurls = true
copyright = "Copyright © 2008–2021, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 5
theme = "alageek"
title = "HENDRY"

[params]
copyright = "© 2021 by Hendry"
copyrightUrl = "https://hendry.xyz"
description = "Portfolio website for simanga Hendry Khoza"
faviconfile = "/image.png"
latestpostcount = 5
logofile = "/image.png"
highlightjs = true
highlightjslanguages = [ "bash", "css", "diff", "django", "javascript", "python", "yaml" ]
toc = true
posts_navigation = true
progressively = true
github = "h3ndry"
linkedin = "simanga-hendry-khoza-83a3a318a/"
twitter = "3h3ndry"
email = "h3khoza@gmail.com"

[[params.best_posts]]
title = "How To Download Videos on Udemy Using youtube-dl"
url = "/blog/how_to_download_udemy_videos/"

[[menu.primary]]
identifier = "blog"
name = "Resume"
url = "/resume/sh_khoza_resume.pdf/"
weight = 10

[[menu.primary]]
identifier = "about"
name = "My Work"
url = "https://github.com/h3ndry"
weight = 20

[[menu.secondary]]
identifier = "patreon"
name = "YouTube"
url = "https://www.youtube.com/channel/UC5GA7zWxLqMWaDOFs_wvBQw"
weight = 110

[[menu.secondary]]
identifier = "bmc"
name = ""
url = "https://www.buymeacoffee.com/gokmen"
weight = 120

[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50
